name: soh
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiodns=3.0.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.13.2
  - aiosignal=1.4.0
  - asyncssh=2.21.1
  - attrs=25.4.0
  - bcrypt=5.0.0
  - brotli-python=1.2.0
  - bzip2=1.0.8
  - ca-certificates=2025.10.5
  - certifi=2025.10.5
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - click=8.3.0
  - colorama=0.4.6
  - cryptography=46.0.3
  - cyrus-sasl=2.1.28
  - daiquiri=3.0.0
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - faust-cchardet=2.1.19
  - frozenlist=1.7.0
  - greenlet=3.2.4
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.11
  - iniconfig=2.3.0
  - invoke=2.2.1
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.44
  - ldap3=2.9.1
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.5.2
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - liblzma=5.8.1
  - libnsl=2.0.1
  - libntlm=1.8
  - libpq=18.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=2.41.2
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - multidict=6.6.3
  - ncurses=6.5
  - openldap=2.6.10
  - openssl=3.5.4
  - packaging=25.0
  - paramiko=4.0.0
  - pendulum=3.1.0
  - pip=25.2
  - pluggy=1.6.0
  - propcache=0.3.1
  - psycopg2=2.9.10
  - pyasn1=0.6.1
  - pycares=4.11.0
  - pycparser=2.22
  - pygments=2.19.2
  - pynacl=1.6.0
  - pyopenssl=25.3.0
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.11.14
  - python-dateutil=2.9.0.post0
  - python-gssapi=1.10.1
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pytzdata=2020.1
  - readline=8.2
  - requests=2.32.5
  - setuptools=80.9.0
  - six=1.17.0
  - sqlalchemy=1.4.46
  - time-machine=2.19.0
  - tk=8.6.13
  - tomli=2.3.0
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - wheel=0.45.1
  - yarl=1.22.0
  - zstandard=0.25.0
  - zstd=1.5.7
prefix: /home/servilla/miniconda3/envs/soh
